Styling Main Part
meruyert93/Project_ReDi pull request #2
Opened 2020-10-13 00:30 UTC by meruyert93

* Designed futher main page view 
* Added image 
* Created new section
@keponk @NadezhdaBabenko @golovnevs @mrTim

2020-10-13 10:21 UTC, MrTim reviewed
Left some comments. Lets iterate on those :)

2020-10-13 10:21 UTC, MrTim commented on css/styles.css
> +
you don't need this empty line here.

2020-10-13 10:21 UTC, MrTim commented on css/styles.css
> +
empty line

2020-10-13 10:21 UTC, MrTim commented on index.html
> +                                <li><a href=#></a></li>
hm...what this big list of empty links is for?

2020-10-29 15:37 UTC, MrTim requested changes

2020-10-29 15:37 UTC, MrTim commented on css/styles.css
> +/* .main__item {
Please remove not used code.

2020-10-29 15:37 UTC, MrTim commented on index.html
> +                        <!-- <div class="main_categories">
Same here: if you don't use it -> remove it

2020-10-29 15:37 UTC, MrTim commented on index.html
> +        <!-- <div class="row">
Same here and please check the rest of the code for not used and commented code.

2020-10-29 15:37 UTC, MrTim commented on js/scripts.js
> +
one empty line is enough as a separator.

2020-10-29 15:37 UTC, MrTim commented on js/scripts.js
> +const api_url = fetch('https://www.edeka.de/eh/service/eh/offers');
this is not an api url, it's a function)
I think you wanted to have something like:
`const apiUrl = 'https://www.edeka.de/eh/service/eh/offers';`

2020-10-29 15:37 UTC, MrTim commented on js/scripts.js
> +api_url
And then right here you will use it like this:
`fetch(apiUtl).then(...)...`

2020-11-11 11:55 UTC, meruyert93 reviewed
- Added the second page

- Connected Locations store API

- Connected Google Map API

- Designed the second page

- Iterated through the locations API to show them in the list

- Finished with carousel to display products from products API

@mrTim @NadezhdaBabenko @golovnevs

2020-11-11 11:55 UTC, meruyert93 commented on index.html
> +                                <li><a href=#></a></li>
I thought I will put there the list of various  products  in the market. However, now I started to think can I get specific products from my API. I am not sure about it maybe I should discuss it with you later on slack, when you have time @mrTim

2020-11-11 11:55 UTC, meruyert93 commented on css/styles.css
> +
okay, I will delete them :)

2020-11-11 17:15 UTC, MrTim requested changes
Please clean up the code a bit in mentioned places :)

2020-11-11 17:15 UTC, MrTim commented on index.html
> +                                <li><a href=#></a></li>
I think you can get rid of these for now and of will be needed you can always add those.

2020-11-11 17:15 UTC, MrTim commented on index.html
> +                                <span>FRUIT FRESH</span>
I think you don;t need to hardcode this product in here, because you'll got products from api

2020-11-11 17:21 UTC, MrTim requested changes
Same here: please clean up the code and adjust var vs const/let situation

2020-11-11 17:21 UTC, MrTim commented on js/scripts.js
> +                            // dots:false
please get rid of these commented lines

2020-11-11 17:21 UTC, MrTim commented on js/scripts.js
> +
too many empty lines

2020-11-11 17:21 UTC, MrTim commented on js/scripts.js
> +// const StoresList = document.getElementById("stores-list");
commented code

2020-11-11 17:21 UTC, MrTim commented on js/scripts.js
> +const LocationApiUrl = fetch('https://www.edeka.de/api/marketsearch/markets');
as I wrote earlier - this is not a url :)
url is 'https://www.edeka.de/api/marketsearch/markets' and this is fetching data what is in your constant.
So I can suggest to store only url in a variable and then below have
```js
fetch(apiUrl)
  .then()
  .then()
```

2020-11-11 17:21 UTC, MrTim commented on js/scripts.js
> +
a lot of empty lines and commented code. Please clean it up)

2020-11-11 17:21 UTC, MrTim commented on js/scripts.js
> +            var nameSupermarket = object.markets[i].name;
you're mixing up var, const and let. Please try to keep your attention to that and use const and let only, since it's a part of new standard

2020-11-11 17:22 UTC, MrTim commented
@meruyert93 Great progress! But let's make your code looks a bit better :) So please take a look at my comments, adjust and push changes and I'll check it again!

2020-11-13 15:11 UTC, merged